platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - npm install npm -g
  - npm install
  - npm prune

build: off

test_script:
  - npm run test